@host = http://127.0.0.1:1239


###
GET  {{host}}/


###
POST {{host}}/
Content-Type: application/json

{
    "plasmid_name":   "test",
    "dna_sequenz":    "ATATTATA"

}

###
POST  {{host}}/api/v1/job/delete
Content-Type: application/json

{
        "id": "3c8a0c73-b7b2-44de-bd28-6cf7eda9b8ab", 
        "secret": "NLawAHdcaUmsklGFq2GjVTVOYzlxk4Ix"
}